### ISSUE TITLE
Installation of Cardinal 2.2 fails

### ISSUE THREAD

**Issue by Seveler** [kuwisdelu/Cardinal#42]
Hello,
i am currently trying to install Cardinal 2.2 by first installing Bioconductor 3.9 (which should contain Cardinal 2.2) and then Cardinal with

`BiocManager::install("Cardinal")`

However, this throws the following error:
```
** byte-compile and prepare package for lazy loading
Creating a new generic function for ‘processingData<-’ in package ‘Cardinal’
Creating a new generic function for ‘centroided<-’ in package ‘Cardinal’
Creating a new generic function for ‘filter’ in package ‘Cardinal’
Creating a new generic function for ‘summarize’ in package ‘Cardinal’
Creating a new generic function for ‘arrange’ in package ‘Cardinal’
Creating a new generic function for ‘group_by’ in package ‘Cardinal’
Creating a new generic function for ‘slice’ in package ‘Cardinal’
Error : in method for ‘group_by’ with signature ‘.data="DataFrame"’:  arguments (‘.add’, ‘.drop’) after ‘...’ in the generic must appear in the method, in the same place at the end of the argument list
Error: unable to load R code in package ‘Cardinal’
Execution halted
ERROR: lazy loading failed for package ‘Cardinal’
```

I have no idea how to solve this issue. Is there a way to solve it or maybe another possibility to install Cardinal 2.2?

Kind regards

**Comment by kuwisdelu** [comment]
Cardinal 2.2 is five years old at this point and no longer supported.

It looks like the issue is related to either `dplyr` or changes to S3 generics in R.

I would start by making sure you are using the versions of R and `dplyr` that coincided with Bioconductor 3.9 and Cardinal 2.2. I think these should be 3.6 and 0.8 respectively.

I would suggest using a Docker image of Bioconductor 3.9 but it looks like 3.9 predates the currently supported Docker images.
