### ISSUE TITLE
Cannot pass for loop variables to image()

### ISSUE THREAD

**Issue by DennisJakob** [kuwisdelu/Cardinal#6]
Hi,

I used to plot images with the following code (edited example) passing the mz argument to the image function via a for loop. 
`par(mfrow = c(2,2),
    mar = c(5, 5, 5, 5),
    oma = c(0, 0, 5, 0),
    cex = 0.8)
  for (i in 400:403) {
    image(msi,
          mz = i,
          plusminus = 0.001,
          col.regions = inferno(n = 100),
          colorkey = TRUE)`
I wanted to change my script using Cardinal v2.2.6 and it seems like the mz argument of the image function does not take the variable of the for loop anymore. I know that you implemented the layout function now, but I need to use the par(mfrow=) function to add further labels (e.g. compound name, adduct) to the image. Is there a way to still pass mz via a for loop variable? If this example is not clear enough I can attach my files.

Cheers, Dennis

**Comment by DennisJakob** [comment]
I just figured out that it is working for `MSImageSet` format but not for `MSImagingExperiment`. Do you know why that is?
You probably won't update the `image()` function for the old `MSImageSet` format right? Do have any suggestions how to workaround this issue?

**Comment by kuwisdelu** [comment]
Please try `print(image(msg, mzi=i, ...))`

Similar to graphics from the **lattice** and **ggplot2** packages, the `plot()` and `image()` methods in Cardinal now produce printable objects rather than plotting anything themselves.

This allows for greater flexibility and modularity in the implementation (as well as the ability to store plots as variables) but requires explicitly print()-ing the plots whenever `print()` wouldn't be called implicitly (such as in the body of a `for` loop).

Please let me know if this doesn't work.

**Comment by kuwisdelu** [comment]
Also, if you want to control the layout yourself, you may want to include `layout=FALSE` or `layout=NULL` (they do the same thing) to make sure the auto-layout is suppressed.

**Comment by kuwisdelu** [comment]
There are no plans to change or update any of the methods for `MSImageSet`.

**Comment by DennisJakob** [comment]
Thanks a lot! The `print()` was exactly what I needed.
